# Generated by Django 3.1.4 on 2020-12-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unnamed question', max_length=100)),
                ('text', models.TextField()),
                ('answer', models.TextField(default='No answer yet')),
            ],
        ),
    ]
